name: mobility_hack_konstanz
description: A Flutter Application for the hack konstanz
repository: https://github.com/SamuelRioTz/mobility_hack_konstanz
issue_tracker: https://github.com/SamuelRioTz/mobility_hack_konstanz/issues

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
    
  mqtt_client: ^9.3.1
  trufi_core:
    path: ../../trufi-core

  vector_tile:
    git:
      url: https://github.com/trufi-association/dart-vector-tile.git
      ref: fc916fd067cb4e64ab782e6249b4e296c7dba913


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
      - assets/cfg/
      - assets/data/
      - assets/images/
